name: Ejecutar pruebas PetStore
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  karate-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el código
        uses: actions/checkout@v3
      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: temurin
      - name: Ejecutar pruebas Karate
        run: mvn test -Dtest=PetTestRunner
